name: CICD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test --parallel --build-cache --daemon --configure-on-demand

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: |
          docker build --platform linux/amd64 \
            --build-arg DB_URL=${{ secrets.DB_URL }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg JWT_ISSUER=${{ secrets.JWT_ISSUER }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg DEPLOY_SECRET_TOKEN=${{ secrets.DEPLOY_SECRET_TOKEN }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/backend_server .

      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend_server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set target IP # 현재 실행 중인 서버 확인
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_SECRET_TOKEN }}" "http://${{ secrets.BACKEND_SERVER_IP }}/env")
          echo "HTTP STATUS: $STATUS"
          
          if [ "$STATUS" = "200" ]; then
            CURRENT_UPSTREAM=$(curl -s -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_SECRET_TOKEN }}" "http://${{ secrets.BACKEND_SERVER_IP }}/env")
          else
            CURRENT_UPSTREAM=green
          fi
          
          echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
          
          if [ "$CURRENT_UPSTREAM" = "blue" ]; then
            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          else
            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          fi
          
      - name: Deploy with Docker Compose # 새로운 서버 배포
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ubuntu
          host: ${{ secrets.BACKEND_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend_server:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d --scale backend=1

      - name: Check deploy server URL # 배포된 서버가 정상 작동하는지 확인
        run: |
          set +e
          for i in {1..5}; do
            STATUS=$(curl -o /dev/null -w "%{http_code}" -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_SECRET_TOKEN }}" "http://${{ secrets.BACKEND_SERVER_IP }}:${{env.STOPPED_PORT}}/env")
            if [ "$STATUS" -eq 200 ]; then
              echo "Health check successful!"
              exit 0
            fi
            echo "Health check failed. Retrying in 10 seconds..."
            sleep 10
          done
          echo "Health check failed after 5 attempts."
          exit 1

      - name: Change nginx upstream # Nginx를 통해 새 서버로 트래픽 전환
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ubuntu
          host: ${{ secrets.BACKEND_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 

      - name: Stop current server # 기존 서버 정리 (중단된 컨테이너 삭제)
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ubuntu
          host: ${{ secrets.BACKEND_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker system prune -f # 사용하지 않는 컨테이너 및 이미지 정리
